export interface ContractTemplate {
  id: string;
  title: string;
  category: string;
  scope: string;
  rate: string;
  schedule: string;
  ownership: string;
  clauses: string[];
}

export const CONTRACT_TEMPLATES: ContractTemplate[] = [
  {
    id: "web-design",
    title: "Freelance Web Design Agreement",
    category: "Design",
    scope: "Creation of responsive web layouts, UI wireframes, style guide, and high-fidelity prototypes in Figma for the Client's primary business website, consisting of up to 5 unique pages.",
    rate: "$3,500 Flat Fee",
    schedule: "50% deposit upfront, 50% upon final layout approval and Figma file transfer.",
    ownership: "All design assets, layout files, and Figma prototypes transfer to the Client upon final payment receipt. The Designer retains the right to display the final designs in their professional portfolio.",
    clauses: [
      "Revision Policy: Up to three (3) rounds of revisions are included in the scope. Additional design revisions will be billed at a rate of $80/hour.",
      "Project Delay: If the Client fails to provide feedback or assets for more than 14 consecutive days, the Designer reserves the right to pause and reschedule the project."
    ]
  },
  {
    id: "frontend-dev",
    title: "Frontend Development Agreement",
    category: "Development",
    scope: "Implementation of responsive frontend components using React, Tailwind CSS, and TypeScript according to the provided Figma guidelines, including code integration with local state management.",
    rate: "$75 / hour",
    schedule: "Billed bi-weekly with detailed time tracking sheets, net 14-day payment term.",
    ownership: "Contractor transfers all intellectual property rights for the developed code to the Client immediately upon successful processing of corresponding payments.",
    clauses: [
      "Code Standards: Code must adhere to industry-standard eslint rules, compile without warnings, and include standard component documentation.",
      "Browsers Compatibility: Layouts will be tested and optimized for the latest version of Chrome, Safari, Firefox, and Edge."
    ]
  },
  {
    id: "copywriting-seo",
    title: "SEO Copywriting Contract",
    category: "Writing",
    scope: "Drafting 8 optimized blog posts (1,500 words each) targeting primary industry keywords, including meta descriptions, structured headers, and internal linking suggestions.",
    rate: "$2,000 Flat Fee",
    schedule: "$1,000 upfront deposit, $1,000 upon delivery and SEO compliance review of all 8 posts.",
    ownership: "The Client acquires full copyright and ownership of the articles upon payment clearance. The Writer shall not republish the content elsewhere.",
    clauses: [
      "Originality Guarantee: The Writer warrants that all content is original, human-written, free of plagiarism, and not generated by automated tools without disclosure.",
      "Fact-checking: The Writer is responsible for factual accuracy and sourcing credible references for claims made in the articles."
    ]
  },
  {
    id: "social-media",
    title: "Social Media Management Agreement",
    category: "Marketing",
    scope: "Curation, scheduling, and posting of 12 high-quality media updates per month on Instagram and LinkedIn, including caption copywriting, hashtag research, and comment engagement for the first hour of posting.",
    rate: "$1,200 / month",
    schedule: "Monthly retainer payable on the 1st of each service month.",
    ownership: "All graphic assets, written copy, and curated media are owned by the Client. Logins and profiles remain strictly confidential.",
    clauses: [
      "Performance Metrics: Monthly engagement and growth analytics report will be provided to the Client within 5 days of the following month.",
      "Content Approval: All content calendars must be submitted to the Client 7 days prior to scheduling. Approval is deemed granted if no feedback is received within 48 hours."
    ]
  },
  {
    id: "video-editing",
    title: "Video Editing Agreement",
    category: "Video",
    scope: "Post-production editing for 5 YouTube videos (10-15 minutes each), including color grading, audio enhancement, text overlays, b-roll insertion, and copyright-free background music integration.",
    rate: "$250 per video",
    schedule: "Paid per completed draft delivery. Final unwatermarked exports shared upon payment clearance.",
    ownership: "Full digital distribution rights are transferred to the Client. Editor retains the right to use short excerpts for their editing showreel.",
    clauses: [
      "Revision Limits: Each video includes two (2) complimentary structural editing rounds. Major scope shifts or subsequent changes incur a flat $50 edit fee.",
      "Source Files: Retaining raw project files (.prproj or .fcpx) remains with the Editor unless a premium buy-out fee of $150 per project is paid."
    ]
  },
  {
    id: "logo-brand",
    title: "Logo & Brand Identity Contract",
    category: "Design",
    scope: "Design of a primary corporate logo, secondary logo lockup, color palette, typography guidelines, and a 12-page comprehensive brand identity guide PDF.",
    rate: "$1,800 Flat Fee",
    schedule: "33% deposit upfront, 33% upon concept selection, 34% upon delivery of final vector files.",
    ownership: "The Client owns all rights to the chosen final vector logo design. The Designer retains ownership of all discarded draft concepts and raw working files.",
    clauses: [
      "Trademark Disclaimer: The Designer is not responsible for conducting trademark searches or legal registrations. Trademark filing is the sole responsibility of the Client.",
      "Portfolio Display: The Designer may publish the finalized branding case study on platforms like Behance, Dribbble, or their personal website."
    ]
  },
  {
    id: "seo-consulting",
    title: "SEO Optimization Consultation Contract",
    category: "Marketing",
    scope: "Conducting a comprehensive SEO audit of the Client website, identifying technical errors, speed bottle-necks, backlink profiles, and compiling a 20-page step-by-step optimization roadmap.",
    rate: "$150 / hour",
    schedule: "Billed upon delivery of the roadmap document, due within 10 days of invoice.",
    ownership: "The audit and strategy roadmap documents belong to the Client for internal deployment.",
    clauses: [
      "No Ranking Guarantee: The Consultant provides expert recommendations based on current search engine guidelines but cannot guarantee specific rankings or organic traffic gains.",
      "Confidentiality: Any internal Google Search Console or Analytics data shared by the Client will be kept strictly confidential and never disclosed to third parties."
    ]
  },
  {
    id: "tech-writing",
    title: "Technical Writing Agreement",
    category: "Writing",
    scope: "Drafting API integration documentation, developer quick-start guides, and interactive code snippet explanations for the Client's cloud SDK deployment.",
    rate: "$90 / hour",
    schedule: "Weekly invoicing with net 15-day terms, capped at a maximum of 40 hours total.",
    ownership: "All documentation, markdown files, and code explanations belong to the Client once payments are settled.",
    clauses: [
      "Technical Accuracy: The Writer will coordinate with the Client's engineering team to verify exact code behavior and accuracy of endpoints before final signoff.",
      "Markdown Format: Deliverables must be formatted in clean markdown compliant with standard documentation parsers."
    ]
  },
  {
    id: "photography",
    title: "Corporate Photography Session Contract",
    category: "Creative",
    scope: "A half-day (4-hour) on-site corporate photoshoot including individual executive headshots, team action shots, and office environment images, with at least 50 professionally retouched final photos.",
    rate: "$1,500 Flat Fee",
    schedule: "50% non-refundable booking deposit, remaining 50% upon delivery of the digital web gallery link.",
    ownership: "The Client is granted a perpetual, non-exclusive commercial license to use, publish, print, and distribute the images. The Photographer retains the authorship copyright.",
    clauses: [
      "Model Releases: The Client represents that all employees photographed have signed or agreed to standard internal model release terms for promotional use.",
      "Weather & Postponement: In the event of extreme weather or force majeure, the session can be rescheduled once with no penalty within 30 days."
    ]
  },
  {
    id: "uiux-consulting",
    title: "UI/UX Design Consultation Contract",
    category: "Design",
    scope: "Conducting heuristic evaluation of the Client's current mobile application, hosting three 1-hour feedback workshops, and compiling a visual checklist of UX improvements.",
    rate: "$120 / hour",
    schedule: "50% upfront, 50% upon delivery of the final UX audit checklist report.",
    ownership: "The Client holds full intellectual rights to the resulting workshop summaries and heuristic recommendations.",
    clauses: [
      "Deliverable Format: Workshop notes and visual checklists will be shared via Notion and downloadable PDF.",
      "Cancellation: Either party may terminate the consultation with a 5-day written notice, subject to billing for actual hours accrued."
    ]
  },
  {
    id: "mobile-dev",
    title: "Mobile App Development Agreement",
    category: "Development",
    scope: "Development of cross-platform React Native features, integration of push notification services, and assistance in deploying test builds on TestFlight and Google Play Console.",
    rate: "$85 / hour",
    schedule: "Milestone-based payments: $2,000 upon initial boilerplate setup, $3,000 upon feature completion, balance upon successful app store submission.",
    ownership: "The mobile app source code, custom assets, and store listings belong to the Client. Third-party dependencies are licensed under their respective opensource licenses.",
    clauses: [
      "App Store Approval: The Contractor will perform standard troubleshooting to meet App Store and Play Store review guidelines, but does not guarantee immediate acceptance by platforms.",
      "Post-Launch Warranty: A 30-day bug-fix support period is provided post-launch for any critical crashes related to the deliverables."
    ]
  },
  {
    id: "business-consulting",
    title: "General Business Consulting Agreement",
    category: "Consulting",
    scope: "Providing strategic advisory services regarding business restructuring, quarterly operational review, marketing scaling strategy, and monthly financial performance assessment.",
    rate: "$2,500 / month",
    schedule: "Retainer paid in advance on the 1st of each calendar month.",
    ownership: "Client retains all proprietary business plans, financial records, and operational spreadsheets created during the consultation engagement.",
    clauses: [
      "Status of Consultant: The Consultant acts as an independent contractor, not an employee, agent, or partner of the Client. No employee benefits or tax withholdings apply.",
      "Limitation of Liability: The Consultant's liability for any direct operational claims is capped at the total amount paid by the Client during the previous 3 months."
    ]
  },
  {
    id: "virtual-assistant",
    title: "Virtual Assistant Agreement",
    category: "Admin",
    scope: "Inbox sorting, calendar scheduling, corporate travel booking, customer email response dispatching, and basic spreadsheet data organization for up to 15 hours per week.",
    rate: "$30 / hour",
    schedule: "Billed weekly via electronic invoice, payment due immediately upon receipt.",
    ownership: "Any internal templates, spreadsheets, or processes optimized remain the exclusive intellectual property of the Client.",
    clauses: [
      "Strict Confidentiality: The Assistant will have access to sensitive contact information and passwords. Under no circumstances will any data or credentials be shared or stored in public vectors.",
      "Holiday Rates: Services requested on official public holidays will be billed at 1.5 times the standard rate."
    ]
  },
  {
    id: "translation",
    title: "Professional Translation Services Agreement",
    category: "General Gig",
    scope: "Translating a 15,000-word software user manual from English to Spanish, ensuring technical terminology is accurate and formatted in clean PDF layout.",
    rate: "$0.12 per word",
    schedule: "50% upfront, remaining 50% upon final delivery of translated documents.",
    ownership: "The translated materials and custom glossary belong exclusively to the Client.",
    clauses: [
      "Glossary of Terms: The Translator will build a technical glossary for the Client's approval to maintain consistency across translations.",
      "Proofreading: All translations undergo dual-pass proofreading by a certified secondary linguist prior to shipment."
    ]
  },
  {
    id: "tutoring",
    title: "Private Academic Tutoring Contract",
    category: "General Gig",
    scope: "Providing 1-on-1 private college-prep chemistry tutoring sessions of 90 minutes each, including custom practice problems and review of exam coursework.",
    rate: "$60 per session",
    schedule: "Payable via digital transfer prior to the start of each weekly session.",
    ownership: "All customized study guides and practice quizzes are licensed to the Student for individual personal use only.",
    clauses: [
      "Cancellation Policy: Cancellations must be made at least 24 hours in advance. Failure to notify within 24 hours will result in a full session charge.",
      "Academic Integrity: The Tutor will explain concepts and guide learning, but will not write essays, take exams, or directly complete homework assignments for the student."
    ]
  },
  {
    id: "audio-mixing",
    title: "Audio Mixing & Mastering Agreement",
    category: "Audio",
    scope: "Professional audio mixing, stereo mastering, vocal pitch tuning, and noise-floor cleaning for a 4-track musical EP (maximum 18 tracks per song).",
    rate: "$800 Flat Fee",
    schedule: "$400 upfront, $400 upon delivery of high-resolution 24-bit WAV master files.",
    ownership: "The master audio files belong to the Artist. The Engineer is credited in metadata as 'Mix & Master Engineer' unless requested otherwise.",
    clauses: [
      "Revision Policy: Two (2) stems adjustment rounds are included per song. Re-mixing due to late replacement of raw recorded audio stems is billed at $50/hour.",
      "Storage Duration: The mixing engineer will keep backup copies of the multitrack session files for up to 180 days after project completion."
    ]
  },
  {
    id: "graphic-retainer",
    title: "Graphic Design Retainer Agreement",
    category: "Design",
    scope: "Ad-hoc graphic design tasks including banner updates, marketing flyer assets, presentation deck polishing, and sales sheet designs up to 20 hours per month.",
    rate: "$1,000 / month",
    schedule: "Retainer payable on the 1st of each month. Unused hours do not roll over to subsequent months.",
    ownership: "All finalized export graphics are owned by the Client. Raw design working files (.ai, .psd) are transferred upon request.",
    clauses: [
      "Turnaround Time: Standard design requests require a minimum of 48 hours business notice. Critical priority requests will be accommodated based on availability.",
      "Overages: Hours exceeding 20 in any calendar month will be pre-notified and billed at an overage rate of $65/hour."
    ]
  },
  {
    id: "ecommerce-setup",
    title: "E-commerce Store Setup Contract",
    category: "Development",
    scope: "Shopify store creation, custom theme configuration, setup of up to 25 primary products, payment gateway integration, shipping rule configuration, and pixel tracking setup.",
    rate: "$2,500 Flat Fee",
    schedule: "40% upfront deposit, 40% on product listing completion, 20% on store launch and hand-off.",
    ownership: "The entire digital storefront and transfer of administrative ownership belong to the Client upon final invoice settlement.",
    clauses: [
      "Platform Fees: The Client is solely responsible for shopify subscription fees, custom app charges, and transaction merchant fees.",
      "Training: Includes a 1-hour screen-share training session to walk the Client through order fulfillment and basic store updates."
    ]
  },
  {
    id: "pr-consulting",
    title: "Public Relations Strategy Contract",
    category: "Marketing",
    scope: "Drafting 2 press releases, identifying 50 targeted industry journalists, managing media outreach campaigns, and compiling weekly coverage clippings.",
    rate: "$2,000 / month",
    schedule: "Billed monthly, net 15 days from invoice issuance date.",
    ownership: "Drafts and target lists prepared specifically for the Client become property of the Client upon invoice payment.",
    clauses: [
      "Media Placement: The PR Consultant warrants professional execution of outreach but cannot guarantee placement in specific publications, as editorial decisions rest with the media outlets.",
      "Crisis Response: Urgent public crisis strategy requests outside normal hours will be billed at double the standard prorated rate."
    ]
  },
  {
    id: "voiceover",
    title: "Professional Voiceover Service Agreement",
    category: "Audio",
    scope: "Recording a professional voiceover of a 3-minute corporate explainer video script, providing clean wav audio file, removing breathes, and delivering two variations of tone.",
    rate: "$300 Flat Fee",
    schedule: "100% prepaid prior to release of the clean, un-watermarked audio files.",
    ownership: "The Client acquires standard commercial digital buyout rights. Broadcast television or radio use requires separate licensing residuals.",
    clauses: [
      "Script Revisions: Script changes after the voiceover has been recorded will require a re-recording fee of $50 per script paragraph.",
      "Pronunciation Guide: The Client must provide a phonetic guide for any specialized acronyms or brand names prior to recording."
    ]
  },
  {
    id: "wordpress-maint",
    title: "WordPress Website Maintenance Agreement",
    category: "Development",
    scope: "Weekly theme and plugin updates, database optimization, daily cloud backups, security firewall monitoring, and 1 hour of emergency content edits per month.",
    rate: "$150 / month",
    schedule: "Auto-recurring charge on the 1st of each service period.",
    ownership: "The website and any maintenance scripts remain the property of the Client.",
    clauses: [
      "Liability for Updates: The Contractor is not liable for plugin incompatibility breaks, but will restore the site from the latest clean backup within 4 hours at no extra cost.",
      "Security Audits: Includes installation of security tools to scan for malware, SQL injection attempts, and suspicious user logins."
    ]
  },
  {
    id: "interior-design",
    title: "Interior Design Consultation Contract",
    category: "Creative",
    scope: "Providing spatial planning, mood boards, color palette suggestions, and a shopping list of furniture pieces for a residential living room and dining area.",
    rate: "$1,200 Flat Fee",
    schedule: "50% upfront deposit, 50% upon electronic delivery of the final visual mood board package.",
    ownership: "The mood boards and spatial layouts are for the Client's personal use. The Designer maintains creative catalog rights.",
    clauses: [
      "Purchasing Agent: The Designer provides specifications but is not responsible for placing orders, coordinate shipping, or handling returns of items unless a separate procurement fee is negotiated.",
      "Contractor Services: Any carpentry, painting, or physical installations are the sole responsibility of licensed local third-party contractors."
    ]
  },
  {
    id: "database-admin",
    title: "Database Administration Contract",
    category: "Development",
    scope: "Configuring a highly available PostgreSQL cluster, optimizing complex slow-query indices, setting up daily automated backup schemas, and auditing user permission groups.",
    rate: "$110 / hour",
    schedule: "Billed monthly based on accrued hours, due within 30 days of invoice.",
    ownership: "All custom shell scripts, database configurations, and optimization documentation belong to the Client.",
    clauses: [
      "Data Access Policy: The Administrator will not copy, download, or transfer actual database records containing user PII outside the secure cloud environment.",
      "Emergency Support: High-severity database outages will be responded to within 2 hours of notification, billed at the emergency rate of $150/hour."
    ]
  },
  {
    id: "content-editing",
    title: "Content Editing & Proofreading Agreement",
    category: "Writing",
    scope: "Comprehensive copyediting of a 60,000-word fiction manuscript, correcting grammar mistakes, enhancing sentence structure, and checking for narrative plot-holes.",
    rate: "$1,500 Flat Fee",
    schedule: "$500 deposit upfront, $500 on 50% manuscript review, $500 on final completed manuscript delivery.",
    ownership: "The author retains complete, unfettered copyright and creative control over the written work.",
    clauses: [
      "Style Guide: Work will be edited in accordance with the Chicago Manual of Style (CMS), 17th Edition, unless specified otherwise.",
      "Feedback System: Comments and developmental editing notes will be delivered via inline suggestions in Microsoft Word tracked changes."
    ]
  },
  {
    id: "fitness-training",
    title: "Personal Fitness Training Agreement",
    category: "General Gig",
    scope: "Delivering 10 private fitness training sessions of 60 minutes each, including personalized exercise tracking spreadsheets and weekly macro nutrition targets.",
    rate: "$750 package fee",
    schedule: "100% paid upfront prior to scheduling the first fitness training session.",
    ownership: "The training schedules and meal suggestions are licensed for the personal use of the client.",
    clauses: [
      "Medical Clearance: The client represents that they have obtained proper medical clearance to participate in rigorous physical exercise.",
      "Expiration: All sessions in the 10-pack package must be redeemed within 90 days from the date of initial purchase."
    ]
  },
  {
    id: "event-planning",
    title: "Event Planning Services Agreement",
    category: "General Gig",
    scope: "Coordination of vendors, scheduling of event timeline, budget sheet tracking, on-site setup management, and general support for a 150-person corporate event.",
    rate: "$3,000 Flat Fee",
    schedule: "$1,000 non-refundable retainer, $1,000 midpoint check, $1,000 within 3 days post-event.",
    ownership: "Vendor contact database created for the event is shared with the Client.",
    clauses: [
      "Third Party Fees: The Planner does not pay third-party vendors directly. All catering, rental, and venue invoices will be paid directly by the Client.",
      "Cancellation Term: If the event is canceled by the Client within 14 days of the event, the full flat fee is immediately due to compensate for blocked calendar space."
    ]
  },
  {
    id: "podcast-editing",
    title: "Podcast Audio Editing Agreement",
    category: "Audio",
    scope: "Editing raw audio of 4 podcast episodes per month (up to 60 mins each), cutting filler words, mixing intros/outros, compressing sound, and delivering publish-ready MP3s.",
    rate: "$400 / month",
    schedule: "Paid monthly at the start of each service period.",
    ownership: "All audio publications belong to the Client. Editor may list episodes as portfolio examples.",
    clauses: [
      "Raw Audio Delivery: Raw recorded assets must be provided to the Editor at least 5 business days prior to the desired publish date.",
      "Episode Re-runs: Major re-editing due to script shifts after editorial completion incurs a fee of $45 per episode."
    ]
  },
  {
    id: "email-marketing",
    title: "Email Marketing Campaign Contract",
    category: "Marketing",
    scope: "Designing and copywriting 4 automated email newsletters in Klaviyo, setting up user-segmentation filters, and scheduling automated checkout reminder flows.",
    rate: "$1,500 Flat Fee",
    schedule: "50% upfront, 50% upon successful completion of automation testing and scheduling.",
    ownership: "The email templates, visual graphics, and automation logic are owned entirely by the Client.",
    clauses: [
      "Compliance: Campaigns will strictly adhere to CAN-SPAM and GDPR requirements (including unsubscribe buttons and postal address disclosures).",
      "List Security: The Contractor will never download or sell the Client's subscriber email list to any external network."
    ]
  },
  {
    id: "financial-advisory",
    title: "Financial Consulting Agreement",
    category: "Consulting",
    scope: "Reviewing company balance sheets, optimizing tax strategies, drafting multi-year forecast spreadsheets, and preparing monthly advisory briefs.",
    rate: "$150 / hour",
    schedule: "Invoiced at the end of each month, due within 15 days of invoice date.",
    ownership: "All spreadsheets, models, and forecasts compiled for the Client are owned by the Client.",
    clauses: [
      "No Investment Advice: The Consultant provides operational and financial planning services but is not a registered broker-dealer or investment advisor.",
      "Data Access: The Client is responsible for supplying accurate, up-to-date accounting records for proper financial planning."
    ]
  },
  {
    id: "motion-graphics",
    title: "Motion Graphics Creation Agreement",
    category: "Video",
    scope: "Creation of a 30-second 2D vector animation explainer, including character design, storyboarding, smooth motion transitions, and voiceover synchronization.",
    rate: "$2,000 Flat Fee",
    schedule: "25% on storyboard, 50% on keyframe draft, 25% upon final rendered MP4 delivery.",
    ownership: "The final rendered video belongs to the Client. Discarded drafts and native vector assets remain with the Artist.",
    clauses: [
      "Style Shift: Changes in visual style after storyboard approval will be charged as an out-of-scope fee of $75/hour.",
      "Credits: The Animator may showcase the video in their professional reel after the video has been made public by the Client."
    ]
  },
  {
    id: "cybersecurity-audit",
    title: "Cybersecurity Auditing Contract",
    category: "Consulting",
    scope: "Conducting vulnerability scanning, web-app penetration testing, employee security policy analysis, and delivering a 15-page remediation report.",
    rate: "$3,200 Flat Fee",
    schedule: "50% upfront, 50% upon final delivery of the security audit report.",
    ownership: "The vulnerability report and security policy recommendations are private and belong strictly to the Client.",
    clauses: [
      "Authorized Scan: The Client authorizes the Consultant to perform secure penetration scanning on their network servers for audit purposes.",
      "Disclaimer: While the Auditor conducts thorough scanning, they cannot warrant that the system is 100% immune from future zero-day breaches."
    ]
  },
  {
    id: "custom-illustration",
    title: "Custom Illustration Agreement",
    category: "Design",
    scope: "Drawing 3 custom high-resolution digital illustrations in a watercolor digital art style for use in Client's print publishing book.",
    rate: "$300 per illustration",
    schedule: "Paid per completed illustration, due upon delivery of final high-resolution PNG file.",
    ownership: "Commercial print rights are transferred to the Publisher. Artist retains copyright and can self-promote with the illustrations.",
    clauses: [
      "Sketch Approval: A pencil sketch will be submitted for feedback prior to digital coloring. Revisions to structure after coloring will cost $50.",
      "Delivery Format: 300 DPI high-resolution CMYK print-ready files."
    ]
  },
  {
    id: "market-research",
    title: "Market Research Consulting Contract",
    category: "Consulting",
    scope: "Conducting user focus interviews, evaluating primary competitor products, collecting consumer pricing data, and drafting a comprehensive market study report.",
    rate: "$95 / hour",
    schedule: "Billed bi-weekly with timesheets, payment due within 14 days of receipt.",
    ownership: "All raw survey databases and competitive research reports belong to the Client.",
    clauses: [
      "Data Validity: Consultant utilizes professional polling methods but does not guarantee specific commercial sales outcomes based on survey analysis.",
      "Survey Expenses: Any paid user recruitment ads or incentive gift cards are pre-approved and paid directly by the Client."
    ]
  },
  {
    id: "catering-service",
    title: "Event Catering Service Agreement",
    category: "General Gig",
    scope: "Preparing and serving a buffet-style dinner for 80 guests, including appetizers, 3 main courses, non-alcoholic drinks, and table cleanup.",
    rate: "$4,500 Flat Fee",
    schedule: "$1,500 non-refundable ingredients deposit, remaining balance due 48 hours prior to the event kickoff.",
    ownership: "Any custom recipes prepared are proprietary to the Caterer.",
    clauses: [
      "Final Guest Count: The Client must provide the final guest count 7 days prior to the event. Adjustments after this window will not decrease the total bill.",
      "Allergy Disclaimer: The Client is responsible for reporting any severe dietary allergies to the Caterer at least 10 days in advance."
    ]
  },
  {
    id: "music-composition",
    title: "Original Music Composition Contract",
    category: "Audio",
    scope: "Composing and recording a 2-minute original electronic theme track for the Client's corporate training video presentation.",
    rate: "$600 Flat Fee",
    schedule: "50% deposit, 50% upon delivery of final stereo master files.",
    ownership: "Artist retains the intellectual composition copyright but grants Client an exclusive, unlimited worldwide license to sync and play the audio.",
    clauses: [
      "Instrumental Stems: Includes delivery of separate drum, synth, and bass stems upon request.",
      "Royalty Free: No secondary broadcast or performance royalties are due to the Artist for the specified corporate video use."
    ]
  },
  {
    id: "blog-drafting",
    title: "Regular Blog Content Drafting Agreement",
    category: "Writing",
    scope: "Researching and drafting 4 monthly educational articles (1,000 words each) on modern financial topics, optimized for SEO headers.",
    rate: "$600 / month",
    schedule: "Retainer billed monthly, paid on the last day of each active blogging month.",
    ownership: "Full digital copyright transfers to the Publisher upon monthly invoice clearance.",
    clauses: [
      "SEO Metadata: Includes writing optimized titles, meta tags, and alt text suggestions for all embedded images.",
      "Two Revisions: Includes up to two rounds of spelling, layout, and structural revisions per article."
    ]
  },
  {
    id: "legal-consultation",
    title: "Legal Administrative Advisory Agreement",
    category: "Consulting",
    scope: "Reviewing commercial lease templates, organizing corporate filing compliance checklists, and providing administrative legal advisory notes.",
    rate: "$200 / hour",
    schedule: "$1,000 upfront retainer, billed against actual logged hours, topped up when retainer falls below $200.",
    ownership: "Memorandums and audit notes belong to the Client for corporate compliance use.",
    clauses: [
      "No Formal Representation: This agreement is for advisory services and does not establish a formal courtroom litigation representation or legal attorney-of-record status.",
      "Conflict of Interest: The Advisor warrants that they do not represent competitors on active opposing litigation."
    ]
  },
  {
    id: "videography",
    title: "Event Videography Contract",
    category: "Video",
    scope: "6 hours of continuous raw 4K video recording on-site at the Client's corporate launch, delivering a 3-minute cinematic highlight video within 14 days.",
    rate: "$2,200 Flat Fee",
    schedule: "50% booking retainer, 50% upon delivery of the final digital download link.",
    ownership: "Client acquires full rights to use and edit the highlight video. Videographer retains raw footage ownership unless purchased separately.",
    clauses: [
      "Event Access: Client is responsible for securing videographer entry, press badges, and suitable safe storage area for camera gear during the event.",
      "Audio Feeds: Client must coordinate with the AV technician to ensure soundboard line output is accessible for recording clean keynote audio."
    ]
  },
  {
    id: "software-qa",
    title: "Software Quality Assurance Contract",
    category: "Development",
    scope: "Writing automated testing suites in Playwright, executing manual regression test scripts, filing bug tickets in Jira, and verifying deployment patches.",
    rate: "$65 / hour",
    schedule: "Billed weekly with detailed logs of tests passed and tickets filed, net 14 terms.",
    ownership: "Test code, custom frameworks, and documentation belong strictly to the Client.",
    clauses: [
      "Regression Logs: A detailed build-health summary will be emailed to the product manager after every major QA sweep.",
      "Critical Bugs: High-severity deployment bugs will be flagged in instant communication channels immediately upon discovery."
    ]
  },
  {
    id: "hr-consulting",
    title: "Human Resources Consulting Agreement",
    category: "Consulting",
    scope: "Drafting a 35-page employee handbook template, structuring hiring pipeline guidelines, and preparing compliant onboarding questionnaires.",
    rate: "$140 / hour",
    schedule: "50% deposit upfront, balance due upon delivery of completed HR handbook PDF.",
    ownership: "The completed custom employee handbook belongs exclusively to the Client for internal corporate use.",
    clauses: [
      "Compliance Disclaimer: The Handbook is structured based on state employment guidelines but should be audited periodically for local updates.",
      "No Legal Advice: The Consultant provides operational HR advisory services and does not act as certified employment counsel."
    ]
  },
  {
    id: "influencer-post",
    title: "Social Media Influencer Content Contract",
    category: "Marketing",
    scope: "Publishing 1 dedicated Instagram feed post and 2 Instagram story slides featuring the Client's product, using pre-approved promotional discount codes.",
    rate: "$500 Flat Fee",
    schedule: "50% deposit upfront, 50% within 48 hours of posting with proof of live metrics.",
    ownership: "Influencer retains ownership of their personal social channels. Client holds a 90-day license to re-post the content in paid ads.",
    clauses: [
      "FTC Compliance: Influencer will clearly display visible disclosures (e.g. #ad or #sponsored) at the beginning of post captions as required by FTC.",
      "Exclusivity: Influencer will not post sponsored endorsements for direct competitor products for 14 days post-publication."
    ]
  },
  {
    id: "data-entry",
    title: "Data Entry & Cleanup Agreement",
    category: "Admin",
    scope: "Transcribing customer records from physical documents into Google Sheets, deduplicating contact lists, and verifying email formatting for 8,000 entries.",
    rate: "$25 / hour",
    schedule: "Paid bi-weekly based on actual sheets verified, due net 7 days.",
    ownership: "All databases and sheets are owned exclusively by the Client.",
    clauses: [
      "Accuracy Threshold: The Contractor warrants a minimum data accuracy rating of 99.5%. Errors identified will be corrected at no additional charge.",
      "Secure Disposal: Any physical documents provided will be securely shredded immediately after transcription verify phase."
    ]
  },
  {
    id: "it-support",
    title: "Managed IT Support Agreement",
    category: "Development",
    scope: "Remote server monitoring, email account setup, printer configuration, office network troubleshooting, and security patch installation up to 10 hours/month.",
    rate: "$250 / month",
    schedule: "Monthly billing, due on the 1st of each active support period.",
    ownership: "Any custom network topology diagrams compiled belong to the Client.",
    clauses: [
      "Response SLA: Standard IT assistance tickets will be acknowledged within 4 business hours. Critical server-down tickets within 1 hour.",
      "Hardware Fees: The cost of physical router replacements or computer parts is separate and must be purchased directly by the Client."
    ]
  },
  {
    id: "business-plan",
    title: "Business Plan Drafting Contract",
    category: "Consulting",
    scope: "Drafting a 15-page investor-ready business plan including company description, target market analysis, SWOT diagram, and marketing strategy summary.",
    rate: "$1,500 Flat Fee",
    schedule: "50% deposit, 50% upon delivery of finalized word document and high-fidelity pitch deck PDF.",
    ownership: "The resulting business plan and presentation graphics belong strictly to the Client.",
    clauses: [
      "Financial Projections: The Client is responsible for providing baseline numbers and capital requirements to be incorporated.",
      "Non-Disclosure: The Consultant warrants that the business idea, concepts, and market edge will be held in absolute secrecy."
    ]
  },
  {
    id: "package-design",
    title: "Product Package Design Contract",
    category: "Design",
    scope: "Creating the dieline layout, cardboard box visual artwork, labeling icons, and custom outer packaging layout for Client's new cosmetics line.",
    rate: "$1,600 Flat Fee",
    schedule: "30% upfront, 40% on layout selection, 30% on delivery of press-ready vector files.",
    ownership: "The Client owns all finalized structural package layouts and graphics upon payment. Designer may use render mocks for self-promotion.",
    clauses: [
      "Printer Coordination: The Designer will provide standard vector layouts but is not responsible for physical printing errors or paper stock selection.",
      "Label Compliance: The Client must audit ingredients list and regulatory barcode graphics for compliance before placing print orders."
    ]
  },
  {
    id: "transcription",
    title: "Audio Transcription Agreement",
    category: "Admin",
    scope: "Transcribing 10 hours of raw legal witness interviews into formatted Microsoft Word transcripts, indicating speaker changes and timestamp markers.",
    rate: "$1.50 per audio minute",
    schedule: "Billed upon delivery of each transcript file, due within 10 days of invoice.",
    ownership: "Transcripts are highly confidential and remain property of the hiring counsel.",
    clauses: [
      "Timestamp Markers: Includes timestamp insertions every five minutes or whenever a speaker change is ambiguous.",
      "Strict Confidentiality: The Transcriber warrants that no audio files or written files will be saved on public servers or shared networks."
    ]
  },
  {
    id: "architectural-drafting",
    title: "Architectural Drafting Consultation Contract",
    category: "Creative",
    scope: "Drafting basic 2D CAD layouts and schematic floor plans for a 1,200 sq.ft residential home extension, based on dimensions provided by the Client.",
    rate: "$2,000 Flat Fee",
    schedule: "50% upfront, 50% upon delivery of final architectural PDF and CAD files.",
    ownership: "The drafted floorplans are licensed to the Client specifically for the construction of this single extension project only.",
    clauses: [
      "Engineering Seal: The Designer drafts layout schematics but does not provide official structural engineering seals or building permit approvals.",
      "Site Verification: The Client is responsible for hiring a licensed surveyor to verify soil capacity and exact legal boundary lines."
    ]
  },
  {
    id: "life-coaching",
    title: "Life Coaching Service Agreement",
    category: "Consulting",
    scope: "Conducting 8 personal development coaching calls of 45 minutes each, focusing on career transition planning, productivity routines, and stress management.",
    rate: "$800 package fee",
    schedule: "Prepaid in full prior to scheduling the initial development session.",
    ownership: "Personal templates, goal-setting worksheets, and materials are licensed for the personal use of the client.",
    clauses: [
      "No Medical Therapy: The Coach provides personal development planning and does not offer professional clinical counseling, medical therapy, or psychological treatment.",
      "Cancellation Term: Sessions must be canceled or rescheduled with 24 hours notice, or the session credit is forfeited."
    ]
  },
  {
    id: "search-marketing",
    title: "SEM Advertising Management Contract",
    category: "Marketing",
    scope: "Structuring Google Search Ads campaigns, bidding optimization, keyword matching, writing 15 text ad variations, and monthly conversion tracking reports.",
    rate: "$800 / month",
    schedule: "Paid monthly at the start of each ad management service period.",
    ownership: "The ad campaign account and assets remain the property of the Client.",
    clauses: [
      "Ad Spend: All actual Google Ads network charges are billed directly to the Client's credit card and are not included in the management fee.",
      "A/B Testing: Includes ongoing budget reallocation based on high-performing ad text variables."
    ]
  },
  {
    id: "general-nda",
    title: "Mutual Non-Disclosure Agreement",
    category: "General Gig",
    scope: "A mutual disclosure agreement to allow the exchange of sensitive business assets, source code repositories, and proprietary algorithms for evaluation.",
    rate: "Gratis / Mutual Exchange",
    schedule: "No fees exchanged. Bound by mutual business interest.",
    ownership: "Each party retains ownership of its own disclosed proprietary information. No licensing or rights are granted under this NDA.",
    clauses: [
      "Term of Secrecy: Disclosed confidential information must be protected with reasonable care and kept secret for a period of three (3) years.",
      "Permitted Use: Receiving party shall use the confidential assets solely to evaluate the prospective business transaction and for no other purpose."
    ]
  },
  {
    id: "unilateral-nda",
    title: "Unilateral Non-Disclosure Agreement",
    category: "NDA",
    scope: "One-way protection of proprietary business information, business models, technical databases, and intellectual properties shared by the Disclosing Party with the Receiving Party.",
    rate: "Gratis / Pre-Collaboration",
    schedule: "No financial transaction. Bound by mutual interest to evaluate a potential business engagement.",
    ownership: "The Disclosing Party retains exclusive ownership of all disclosed proprietary materials, intellectual properties, and trade secrets.",
    clauses: [
      "Definition of Confidential Info: Confidential Information includes all non-public technical, financial, and operational details marked as proprietary or understood to be secret by the nature of disclosure.",
      "Secrecy Duration: The Receiving Party agrees to maintain absolute confidentiality of all disclosed materials for a period of five (5) years from the execution date."
    ]
  },
  {
    id: "contractor-nda",
    title: "Independent Contractor NDA",
    category: "NDA",
    scope: "Non-disclosure and data protection agreement for freelance contractors receiving access to corporate source code, customer records, and internal business frameworks.",
    rate: "Included in Service Retainer",
    schedule: "No independent cost. Part of the main independent contractor engagement terms.",
    ownership: "All internal business assets, database structures, client communications, and server credentials remain the sole intellectual property of the Client.",
    clauses: [
      "Customer Data Privacy: The Contractor agrees not to download, copy, or distribute customer personally identifiable information (PII) to any external server or network.",
      "Destruction of Data: Upon contract termination, the Contractor will permanently delete all local copies of server credentials, project repositories, and client files within 24 hours."
    ]
  },
  {
    id: "employee-nda",
    title: "Standard Employee NDA",
    category: "NDA",
    scope: "Employment-based non-disclosure agreement to protect trade secrets, proprietary workflows, sales pipelines, client rosters, and internal strategy decks from external leakage.",
    rate: "Included in Salary / Employment",
    schedule: "No direct fees. Bound by the terms of employment and receipt of wages.",
    ownership: "The Employer retains full, exclusive ownership of all methods, formulas, codes, strategies, and customer contacts generated or accessed during employment.",
    clauses: [
      "Duty of Confidentiality: The Employee shall not disclose, print, copy, or utilize any trade secrets or proprietary company information outside official duties.",
      "Post-Employment Survival: The obligations of secrecy survive employment termination and remain in effect for three (3) years post-employment."
    ]
  },
  {
    id: "investor-nda",
    title: "Investor Pitch Deck NDA",
    category: "NDA",
    scope: "Non-disclosure agreement restricting potential venture capitalist, angel investor, or lender from sharing pitch decks, financial sheets, and prototype diagrams with third parties.",
    rate: "Gratis / Evaluation Phase",
    schedule: "No financial exchange. Conditioned upon the evaluation of a potential equity or debt investment.",
    ownership: "The Startup retains all rights to the pitch deck, financial tables, patent-pending schemas, and product prototype diagrams.",
    clauses: [
      "Restricted Replication: The Investor shall not copy, transmit, or share the pitch deck or operational figures with any external networks or competitive startups.",
      "Permitted Evaluators: Disclosures may only be shared with the Investor's immediate partners, legal counsel, and financial analysts on a strict need-to-know basis."
    ]
  },
  {
    id: "ma-nda",
    title: "M&A Corporate Evaluation NDA",
    category: "NDA",
    scope: "High-grade mutual non-disclosure and standstill agreement to facilitate due diligence for a potential corporate acquisition, merger, or asset purchase.",
    rate: "Gratis / Corporate Evaluation",
    schedule: "No direct fees. Execution is a prerequisite for opening the secure virtual data room (VDR).",
    ownership: "Each corporation retains absolute title to its own financial audits, customer directories, codebases, and intellectual assets.",
    clauses: [
      "Standstill Provision: The Receiving Party agrees not to solicit, hire, or poach key executives or employees of the Disclosing Party for a period of two (2) years.",
      "Return of Information: If negotiations fail, both parties must certify in writing the permanent erasure of all records exported from the virtual data room."
    ]
  },
  {
    id: "ip-assignment",
    title: "Intellectual Property Assignment Agreement",
    category: "Legal",
    scope: "Complete, worldwide transfer and assignment of all inventions, source codes, patents, trademarks, and creative copyrights from the Developer to the Client.",
    rate: "Included in Work Product Payment",
    schedule: "IP transfer completes immediately upon full settlement of all corresponding project invoice payments.",
    ownership: "All intellectual rights, moral rights, and titles to the developed assets transfer fully and permanently to the Client.",
    clauses: [
      "Further Assurances: The Developer agrees to sign any patent applications, copyright registrations, or trademark filings necessary to perfect the Client's ownership.",
      "Developer Warranty: The Developer warrants that the work product is original, does not infringe third-party IP, and contains no open-source copyleft licenses."
    ]
  },
  {
    id: "non-compete-contract",
    title: "Contractor Non-Compete Agreement",
    category: "Legal",
    scope: "Restrictive covenant preventing the Contractor from working with direct competitors or launching a competing business in the same market vertical during the engagement.",
    rate: "Included in Engagement Fees",
    schedule: "No separate billing. A material condition of the independent contractor service agreement.",
    ownership: "The Client maintains exclusive rights to its proprietary business methods, marketing channels, and client lists.",
    clauses: [
      "Restricted Geography: The Contractor shall not engage in competitive services within the specified territory (e.g. North America) for a duration of one (1) year post-termination.",
      "Vertical Definition: Competition is strictly defined as providing identical database-management tools or software services targeting the same niche."
    ]
  },
  {
    id: "non-solicitation",
    title: "Client & Employee Non-Solicitation Agreement",
    category: "Legal",
    scope: "Legal covenant restricting the service provider from hiring the Client's employees, or pitching services directly to the Client's active customer base.",
    rate: "Gratis / Mutual Protection",
    schedule: "Bound as a covenant within the broader commercial vendor service agreement.",
    ownership: "Client lists, personnel files, and vendor contacts remain proprietary to their respective parties.",
    clauses: [
      "Non-Solicitation of Staff: Neither party will recruit, hire, or solicit any employee of the other party during the term and for twelve (12) months after.",
      "Client Protection: The Provider shall not solicit active clients of the Client whom they became aware of during this engagement."
    ]
  },
  {
    id: "saas-licensing",
    title: "SaaS Software Licensing Agreement",
    category: "Legal",
    scope: "Granting a non-transferable, non-exclusive enterprise license to access and use the SaaS cloud platform for up to 50 active internal corporate users.",
    rate: "$500 / month",
    schedule: "Billed monthly via automatic recurring credit card payment, net 0 term.",
    ownership: "The SaaS vendor retains all ownership, source code, APIs, database architectures, and look-and-feel copyrights of the platform.",
    clauses: [
      "Uptime Commitment: The Vendor guarantees a monthly platform uptime service level agreement (SLA) of 99.9%, excluding pre-scheduled maintenance.",
      "Usage Limits: Exceeding 10,000 monthly API calls will result in automatic overage charges of $0.05 per additional call."
    ]
  },
  {
    id: "affiliate-partnership",
    title: "Joint Affiliate Marketing Partnership",
    category: "Legal",
    scope: "Structuring a marketing partnership where the Affiliate promotes the Client's SaaS platform using custom referral links, tracking cookies, and banners.",
    rate: "30% recurring commission",
    schedule: "Payouts made monthly on the 15th for the previous month's referred sales, subject to a $100 minimum threshold.",
    ownership: "The Client retains complete ownership of branding, domains, and customer relationships. Affiliate owns their content channels.",
    clauses: [
      "Exclusionary Terms: Affiliate will not bidding on the Client's brand terms in Google Search Ads, nor publish spam links on public web forums.",
      "Cookie Duration: Referral sales are tracked using a 30-day attribution cookie window from the user's initial click."
    ]
  },
  {
    id: "ai-model-training",
    title: "AI Model Dataset Training Contract",
    category: "AI & Data",
    scope: "Curating, cleaning, formatting, and preparing a dataset of 50,000 high-quality text-to-SQL pairings for training custom language models.",
    rate: "$5,000 Flat Fee",
    schedule: "30% upfront deposit, 40% on sample validation, 30% upon final JSON database delivery.",
    ownership: "The Client retains exclusive, royalty-free, perpetual ownership of the dataset and all custom weights generated by training the model.",
    clauses: [
      "Data Cleansing: The Datasets must be thoroughly audited to remove any PII, toxic language, or copyright-infringing content.",
      "Verification Sweep: Includes running automated validation checks to verify that 100% of the text-to-SQL queries run error-free."
    ]
  },
  {
    id: "prompt-engineering",
    title: "Prompt Engineering Service Contract",
    category: "AI & Data",
    scope: "Designing, optimizing, and evaluation testing of system prompts and agentic schemas for the Client's customer support LLM pipeline.",
    rate: "$95 / hour",
    schedule: "Billed bi-weekly with detailed spreadsheet timesheets, net 14-day terms.",
    ownership: "The system prompts, vector indexing structures, and custom agent logic belong entirely to the Client upon payment clearance.",
    clauses: [
      "LLM Agnosticism: Prompts will be tested and optimized for Anthropic Claude, OpenAI GPT-4, and Google Gemini models.",
      "Security Protocols: Prompts must incorporate guardrails to prevent jailbreaking, prompt injection attacks, and hallucinated output leaks."
    ]
  },
  {
    id: "vector-db-setup",
    title: "RAG & Vector Database Integration",
    category: "AI & Data",
    scope: "Deploying a Pinecone/Qdrant vector index, writing data ingestion pipelines to chunk internal markdown docs, and connecting the database with a LangChain search api.",
    rate: "$4,000 Flat Fee",
    schedule: "50% upfront deposit, 50% upon successful live search query testing and documentation hand-off.",
    ownership: "The ingestion scripts, deployment layouts, and internal search APIs belong to the Client once paid.",
    clauses: [
      "Chunking Logic: Files will be chunked using semantic splitting with overlapping boundaries to ensure context integrity.",
      "Hosting Costs: The Client is responsible for setting up and paying for cloud hosting (AWS/Vercel) and database node costs directly."
    ]
  },
  {
    id: "llm-finetuning",
    title: "LLM Fine-Tuning Agreement",
    category: "AI & Data",
    scope: "Fine-tuning a Llama-3 8B model using LoRA adapters on Client's customer service logs, including evaluation sweeps and Docker deployment templates.",
    rate: "$6,500 Flat Fee",
    schedule: "$2,500 upfront, $2,000 upon training completion, $2,000 on API deployment and hand-off.",
    ownership: "The fine-tuned model adapters, code configurations, and weights belong to the Client.",
    clauses: [
      "Evaluation Baseline: The fine-tuned model must outperform the base model by at least 15% on target customer response accuracy evaluation datasets.",
      "Model Backup: The Developer will host secure backups of training logs and checkpoints for 60 days following handover."
    ]
  },
  {
    id: "data-science-consulting",
    title: "Predictive Analytics Consulting Contract",
    category: "AI & Data",
    scope: "Analyzing transaction databases, building user churn forecasting models in Python, and delivering a Jupyter notebook dashboard showing user lifetime values.",
    rate: "$130 / hour",
    schedule: "Weekly invoice submissions, payable within 10 business days.",
    ownership: "The predictive algorithms, notebooks, and database visualizations are owned by the Client.",
    clauses: [
      "Data Integrity: The Consultant is not responsible for business revenue drops, but warrants applying standard data engineering methodologies.",
      "Security Shield: All customer transaction logs will be processed in a secure environment and never uploaded to public AI services."
    ]
  },
  {
    id: "data-annotation",
    title: "Audio Data Labeling Agreement",
    category: "AI & Data",
    scope: "Manually transcribing and labeling speaker segments, sentiment nodes, and environmental sounds for 200 hours of raw customer service call audio.",
    rate: "$2.00 per audio minute",
    schedule: "Billed weekly based on verified labeled batch delivery, due net 10 terms.",
    ownership: "All transcription sheets, metadata labels, and audio files are the exclusive property of the Client.",
    clauses: [
      "Label Standard: Data must follow strict formatting (e.g. JSON format with start/end millisecond nodes).",
      "Accuracy Guarantee: Labeled batches with an error rate exceeding 1.5% will be re-processed at the Contractor's cost."
    ]
  },
  {
    id: "firmware-dev",
    title: "IoT Firmware Development Agreement",
    category: "Engineering",
    scope: "Writing C/C++ firmware for ESP32 boards, integrating Wi-Fi connectivity APIs, configuring sensor read cycles, and optimizing low-power deep-sleep states.",
    rate: "$90 / hour",
    schedule: "Milestone based: $3,000 upon hardware-schematic review, balance upon delivery of verified firmware source code.",
    ownership: "Firmware source files, layout scripts, and flashing instructions belong entirely to the Client.",
    clauses: [
      "Over-the-Air Updates: Firmware will support secure OTA updates using encrypted HTTPS endpoints.",
      "Debugging support: Includes 3 months of remote developer support for compiling bug fixes post-launch."
    ]
  },
  {
    id: "pcb-design",
    title: "Electronic PCB Design Contract",
    category: "Engineering",
    scope: "Designing a 4-layer PCB schematic and layout in KiCad, selecting BOM components, and delivering manufacturing-ready Gerber and drill files.",
    rate: "$2,200 Flat Fee",
    schedule: "50% upfront deposit, 50% upon successful delivery of Gerber files and BOM spreadsheets.",
    ownership: "The KiCad project directories, layout schematics, and BOM belong exclusively to the Client.",
    clauses: [
      "DFM Guidelines: The layout will adhere to standard Design for Manufacturing (DFM) rules specified by the Client's chosen manufacturer.",
      "Component Availability: The Designer warrants sourcing easily available parts from suppliers like Mouser or DigiKey to avoid assembly line holds."
    ]
  },
  {
    id: "cad-modeling",
    title: "3D CAD Product Design Contract",
    category: "Engineering",
    scope: "Designing structural enclosures for an electronic consumer product using SolidWorks, ensuring fits for internal PCBs, and exporting files for injection molding.",
    rate: "$80 / hour",
    schedule: "Billed upon milestone completions, net 15 days from invoicing.",
    ownership: "All SolidWorks files, assembly layouts, and STEP models are owned by the Client.",
    clauses: [
      "Draft Angles: Enclosures will incorporate proper draft angles (1.5 to 2 degrees) to allow secure plastic injection mold ejection.",
      "Prototypes Test: Includes adjusting designs based on feedback from up to two rounds of 3D printed prototyping."
    ]
  },
  {
    id: "hardware-testing",
    title: "Hardware QA & Environmental Testing",
    category: "Engineering",
    scope: "Conducting thermal stress tests, signal integrity analysis, power consumption logging, and compiling a hardware test report for the Client's prototype.",
    rate: "$2,500 Flat Fee",
    schedule: "50% upfront, 50% upon delivery of the test logs and environmental audit report.",
    ownership: "Test logs, report sheets, and thermal photos belong to the Client.",
    clauses: [
      "Equipment Access: The Client must supply two fully assembled, functional prototypes along with appropriate testing manuals.",
      "Destructive Testing: The Client acknowledges that prototypes may be pushed beyond thermal limits and damaged during testing."
    ]
  },
  {
    id: "devops-pipeline",
    title: "DevOps CI/CD Automation Contract",
    category: "Engineering",
    scope: "Writing GitHub Actions pipelines, configuring Docker Compose files, deploying a Kubernetes cluster on AWS EKS, and setting up Prometheus metric monitoring.",
    rate: "$110 / hour",
    schedule: "Billed bi-weekly with detailed task breakdowns, net 14-day payment.",
    ownership: "All Terraform scripts, YAML configurations, and automation scripts belong to the Client.",
    clauses: [
      "Zero Downtime: The pipeline must support rolling updates to deploy application containers with zero service downtime.",
      "Secret Management: Infrastructure secrets will be managed using AWS Secrets Manager rather than hardcoded configurations."
    ]
  },
  {
    id: "api-integration",
    title: "B2B API Integration Agreement",
    category: "Engineering",
    scope: "Writing custom Node.js middleware to integrate Salesforce CRM with Client's core transaction API, including webhook handlers and error logs.",
    rate: "$3,000 Flat Fee",
    schedule: "50% upfront deposit, 50% upon deployment to production and 7 days of error-free log monitoring.",
    ownership: "The middleware repository, mapping scripts, and endpoint tests belong exclusively to the Client.",
    clauses: [
      "Rate Limiting: Middleware must handle API rate limits and include automatic exponential backoff retry cycles.",
      "Data Encryption: All data payloads passed between CRM and API must be encrypted in transit using TLS 1.3."
    ]
  },
  {
    id: "influencer-campaign-nda",
    title: "Influencer Campaign Non-Disclosure",
    category: "NDA",
    scope: "Protecting embargo details, unreleased product features, and marketing timelines shared with a social media influencer prior to the campaign launch.",
    rate: "Gratis / Part of Campaign Brief",
    schedule: "No fees. Bound by the promotional influencer service agreement terms.",
    ownership: "The Client maintains exclusive ownership of all unreleased products, branding assets, and marketing guidelines.",
    clauses: [
      "Embargo Timeline: The Influencer shall not post, speak about, or show the product on any platform until the official launch date on October 1st.",
      "Restricted Shares: The Influencer must keep product packaging, designs, and shipping boxes out of background frames in other posts prior to launch."
    ]
  },
  {
    id: "sales-commission",
    title: "Sales Representative Agreement",
    category: "Marketing",
    scope: "Conducting B2B sales outreach, booking demo calls for Client's enterprise software, and closing contract sales in the target territory.",
    rate: "$1,500/mo + 15% Commission",
    schedule: "Retainer paid on the 1st of each month; commissions paid monthly on invoice clearance of referred clients.",
    ownership: "All sales leads, CRM data, and email records are the exclusive property of the Client.",
    clauses: [
      "Exclusivity: The Sales Representative represents that they do not sell competing software systems targeting the same client list.",
      "Commission Cap: Commission is paid on the first year's contract value only, excluding subsequent renewal periods."
    ]
  },
  {
    id: "pitch-deck-design",
    title: "Investor Pitch Deck Design Contract",
    category: "Design",
    scope: "Designing a 12-slide high-fidelity presentation deck in Figma, structuring the narrative flow, writing slide copy, and delivering PDF and PPTX formats.",
    rate: "$2,400 Flat Fee",
    schedule: "50% upfront deposit, 50% upon delivery of final presentations.",
    ownership: "The Client owns the final presentation. Designer retains the right to display layout renders in their portfolio.",
    clauses: [
      "Source Material: The Client must provide all underlying financial spreadsheets and market research figures.",
      "Revision Rounds: Includes up to three (3) rounds of narrative and design reviews based on founder feedback."
    ]
  },
  {
    id: "brand-naming",
    title: "Brand Naming & Identity Strategy",
    category: "Design",
    scope: "Conducting brand research workshops, proposing 15 unique company names, checking domain availability, and executing basic search trademark reviews.",
    rate: "$1,800 Flat Fee",
    schedule: "50% upfront, 50% upon delivery of the brand naming package and chosen domain list.",
    ownership: "The selected brand name and registered domain belong exclusively to the Client. Discarded name ideas are retained by the Designer.",
    clauses: [
      "No Trademark Guarantee: The Designer conducts basic database checks but recommended names should undergo formal audit by a trademark lawyer.",
      "Domain Registry: The Client is responsible for paying registry and subscription fees for the chosen domain."
    ]
  },
  {
    id: "seo-local",
    title: "Local SEO & Map Pack Contract",
    category: "Marketing",
    scope: "Optimizing Client's Google Business Profile, building 50 local citations, tracking map grid positions, and acquiring reviews from past clients.",
    rate: "$600 / month",
    schedule: "Retainer billed monthly on the 1st, due net 10.",
    ownership: "All profiles, optimized media, local citations, and databases remain under the Client's control.",
    clauses: [
      "Review Guidelines: The Contractor will guide review acquisition in accordance with Google's terms, avoiding fake reviews or paid incentivization.",
      "Monthly Reports: Includes a monthly dashboard tracking call requests, map grid rankings, and website clicks."
    ]
  },
  {
    id: "cro-contract",
    title: "Conversion Rate Optimization (CRO)",
    category: "Marketing",
    scope: "Auditing user click heatmaps, designing A/B landing page variations in Hotjar/VWO, and tweaking Shopify checkout steps to improve conversions.",
    rate: "$120 / hour",
    schedule: "Billed monthly based on logged hours, net 15-day term.",
    ownership: "All custom codes, A/B test scripts, and analytical dashboards belong to the Client.",
    clauses: [
      "Traffic Minimum: The Client is responsible for maintaining standard traffic volumes (minimum 10k visits/mo) for A/B test validity.",
      "Methodology: The Optimizer will implement changes based on statistical significance testing (minimum 95% confidence intervals)."
    ]
  },
  {
    id: "ghostwriting-contract",
    title: "Book Ghostwriting Agreement",
    category: "Writing",
    scope: "Drafting a 40,000-word business leadership memoir based on transcripts from 10 hours of audio interviews with the Author.",
    rate: "$10,000 Flat Fee",
    schedule: "Paid in 4 milestones: 25% upfront, 25% on Outline, 25% on first 20k words, 25% on final draft completion.",
    ownership: "The Author retains 100% exclusive copyright, authorship credits, and future royalties. The Ghostwriter remains completely anonymous.",
    clauses: [
      "Interview Cooperation: The Author agrees to make themselves available for scheduled interviews and provide outline notes.",
      "Confidentiality: The Ghostwriter will never disclose their participation in writing the book to any public network or third party."
    ]
  },
  {
    id: "grant-writing",
    title: "Grant Proposal Writing Agreement",
    category: "Writing",
    scope: "Researching corporate foundations, writing a detailed grant application for a non-profit organization, and preparing budget templates.",
    rate: "$80 / hour",
    schedule: "Weekly timesheets, due within 14 days of invoice.",
    ownership: "The compiled grant proposal and application files belong entirely to the Client.",
    clauses: [
      "No Success Commission: In compliance with professional ethics, the Writer is paid for draft assembly and does not charge a percentage of the awarded grant.",
      "Accurate Data: The Client must supply audited financial reports and program execution records required for the proposal."
    ]
  },
  {
    id: "resume-writing",
    title: "Executive Resume Writing Agreement",
    category: "Writing",
    scope: "Rewriting executive resume, optimizing LinkedIn profile section copy, and drafting a customizable cover letter tailored for executive positions.",
    rate: "$450 Flat Fee",
    schedule: "100% paid upfront prior to scheduling the initial intake call.",
    ownership: "The final resume PDF, DOCX, and profile copy belong exclusively to the Client for personal job application use.",
    clauses: [
      "Timeline: Initial drafts will be shared within 5 business days of the intake call. Review period ends after 14 days.",
      "Review Scope: Includes up to two (2) rounds of textual revision based on candidate feedback."
    ]
  },
  {
    id: "newsletter-mgmt",
    title: "Newsletter Management Contract",
    category: "Writing",
    scope: "Curating, formatting, writing, and scheduling 4 weekly Substack newsletters, including graphic headers and post-send subscriber analysis reports.",
    rate: "$800 / month",
    schedule: "Billed monthly in advance, payable on the 1st of each service month.",
    ownership: "Substack profile, subscriber emails, and all copy belong to the Client. The Writer may list post titles in their portfolio.",
    clauses: [
      "Subscriber Privacy: The Writer will never export or use the subscriber email database for any external purpose.",
      "Copy Approval: Newsletters must be submitted to the Client 3 days before sending. Unapproved posts will not be scheduled."
    ]
  },
  {
    id: "curriculum-design",
    title: "Online Course Curriculum Contract",
    category: "Writing",
    scope: "Designing the module outline, writing script transcripts for 12 video modules, and compiling printable PDF worksheets for a student course.",
    rate: "$3,000 Flat Fee",
    schedule: "40% upfront deposit, 30% upon script approval, 30% upon final worksheet delivery.",
    ownership: "All curriculum blueprints, scripts, and PDFs belong entirely to the Client upon final invoice settlement.",
    clauses: [
      "Pedagogical Standards: Material will be structured to meet standard digital learning guidelines and course metrics.",
      "Formatting: Worksheets will be styled using the Client's brand identity palette and font guidelines."
    ]
  },
  {
    id: "mural-painting",
    title: "Commercial Mural Art Agreement",
    category: "Creative",
    scope: "Designing and painting a custom 15ft x 10ft wall mural inside the Client's corporate lobby space, including wall prep and paint supplies.",
    rate: "$4,500 Flat Fee",
    schedule: "40% deposit to cover supplies, 30% upon sketch selection, 30% upon completion of painting.",
    ownership: "The Client owns the physical mural artwork. The Artist retains creative rights and copyright for digital reproductions.",
    clauses: [
      "Wall Preparation: Client must clear the wall area, repair any structural drywall issues, and ensure proper HVAC airflow prior to kickoff.",
      "Artist Signature: The mural will include a small, legible signature of the Artist in a lower corner."
    ]
  },
  {
    id: "fashion-design",
    title: "Apparel Pattern Design Agreement",
    category: "Creative",
    scope: "Drafting 5 digital apparel pattern dielines in DXF format, creating tech packs, and preparing detailed sizing specifications for manufacturing.",
    rate: "$500 per pattern",
    schedule: "Paid per completed pattern design package, due net 10 terms.",
    ownership: "The pattern vectors and tech packs belong to the Client. Designer retains catalog references.",
    clauses: [
      "Factory Checks: Includes adjusting pattern dielines based on feedback from the client's selected factory sample run.",
      "Sizing Matrix: Tech packs will include detailed specifications for standard sizes XS through XL."
    ]
  },
  {
    id: "voice-acting",
    title: "Voice Acting Services Contract",
    category: "Creative",
    scope: "Recording professional character voice acting tracks for a 5-episode mobile game storyline, delivering clean wav files.",
    rate: "$150 per episode",
    schedule: "Paid per completed episode recording, prior to release of un-watermarked audio assets.",
    ownership: "The Client acquires full digital synchronization rights for use within the mobile game. The Actor retains overall voice-likeness rights.",
    clauses: [
      "Retakes: Up to three (3) retakes for tone or mispronunciation are included per episode. Changes to script cost $10 per line.",
      "Credits: The Voice Actor will be credited in the game's closing credits list under 'Voice Cast'."
    ]
  },
  {
    id: "illustration-retainer",
    title: "Illustration Retainer Agreement",
    category: "Creative",
    scope: "Delivering up to 8 editorial vector illustrations per month for the Client's printed news magazine layouts.",
    rate: "$2,000 / month",
    schedule: "Billed monthly on the last day, payable within 15 days of invoice date.",
    ownership: "The Client acquires exclusive print publication rights for each illustration. Artist retains copyright for portfolio use.",
    clauses: [
      "Deadlines: Standard illustration brief requires a 5 business day notice. Express 24-hour turnaround bills at double the rate.",
      "Style Guide: Illustrations must adhere to the magazine's visual layout guidelines and color palette specifications."
    ]
  },
  {
    id: "makeup-artist",
    title: "Corporate Shoot Makeup Agreement",
    category: "Creative",
    scope: "Providing professional makeup application and hair styling services for up to 8 corporate executives during a team photography session.",
    rate: "$800 Flat Fee",
    schedule: "50% booking retainer to secure dates, 50% paid on-site upon completion of shoot services.",
    ownership: "No intellectual copyrights applicable. Photographic images of makeup work are licensed for the Artist's portfolio display.",
    clauses: [
      "Sanitization: The Artist warrants that 100% of makeup brushes, kits, and tools undergo medical-grade sanitization between clients.",
      "Overages: Additional makeup requests outside the specified 8 executives will be billed on-site at $90 per person."
    ]
  },
  {
    id: "music-mastering",
    title: "Professional Audio Mastering Agreement",
    category: "Audio",
    scope: "Audio mastering for a 10-track musical album, optimizing loudness levels (LUFS) for streaming, and rendering DDP images for CD manufacturing.",
    rate: "$1,200 Flat Fee",
    schedule: "50% upfront deposit, 50% upon delivery of finalized master WAV files.",
    ownership: "Master audio properties are owned by the Artist/Client. The Engineer is credited in album metadata.",
    clauses: [
      "Mastering Targets: Masters will meet standard digital streaming targets (e.g. -14 LUFS, -1 dBTP) unless specified otherwise.",
      "Mix Adjustments: Mastering revisions are free, but re-submitting a new mix file after mastering has completed costs $50 per track."
    ]
  },
  {
    id: "podcast-scriptwriting",
    title: "Podcast Scriptwriting Agreement",
    category: "Audio",
    scope: "Researching and writing full transcripts and narrative show notes for 2 true-crime podcast episodes per month (45-minute runtime each).",
    rate: "$500 per script",
    schedule: "Paid monthly based on completed script delivery, net 14 terms.",
    ownership: "Script files and research notes belong to the Producer. Writer retains the right to be listed as 'Lead Writer' in episode credits.",
    clauses: [
      "Factual Integrity: The Writer must document primary sources and verify names and timelines before submitting the draft.",
      "Formatting: Scripts must be written in standard dual-column audio production format showing sound effect cues."
    ]
  },
  {
    id: "dj-service",
    title: "Corporate DJ Service Agreement",
    category: "Events",
    scope: "Providing professional DJ performance services for 4 hours at the Client's annual gala, including sound system and basic lighting setup.",
    rate: "$1,200 Flat Fee",
    schedule: "30% non-refundable booking deposit, remaining 70% paid prior to performance kickoff.",
    ownership: "Musical track licenses are owned by the DJ. Mix recording of the event belongs to the DJ unless purchased separately.",
    clauses: [
      "Power Requirements: The Client must provide a dedicated 20-amp, 120-volt circuit within 15 feet of the DJ booth setup.",
      "Song Request Guidelines: The Client must share a 'Must Play' and 'Do Not Play' list at least 14 days prior to the event date."
    ]
  },
  {
    id: "live-sound",
    title: "Live Sound Engineering Contract",
    category: "Events",
    scope: "On-site setup of mixing consoles, tuning PA sound systems, performing band soundchecks, and mixing live sound during a 3-hour concert.",
    rate: "$450 Flat Fee",
    schedule: "100% paid on-site upon completion of event services.",
    ownership: "No intellectual copyright transfers. Technical console layouts remain with the Engineer.",
    clauses: [
      "Load-In Window: The Engineer must have access to the venue stage at least 3 hours prior to soundcheck.",
      "Hearing Protection: The Engineer is not responsible for hearing damage claims and will operate the system within local DB limits."
    ]
  },
  {
    id: "property-management",
    title: "Property Management Contract",
    category: "Real Estate",
    scope: "Handling tenant relations, rent collection, coordinate maintenance tasks, and conducting quarterly property walkthroughs for a residential rental home.",
    rate: "10% of Monthly Rent",
    schedule: "Deducted automatically from monthly collected rent prior to transferring remaining funds to the Owner.",
    ownership: "The Owner retains all property deeds and titles. Tenant list and logs belong to the Owner.",
    clauses: [
      "Emergency Repair: The Manager is authorized to schedule emergency repairs up to $500 without prior Owner approval.",
      "Tenant Eviction: The Manager will manage legal eviction processes, with actual attorney and court costs paid by the Owner."
    ]
  },
  {
    id: "real-estate-photo",
    title: "Luxury Real Estate Media Agreement",
    category: "Real Estate",
    scope: "Capturing 30 high-resolution interior/exterior photos, 5 aerial drone photos, and editing a 60-second walkthrough video of a residential listing.",
    rate: "$650 Flat Fee",
    schedule: "100% paid before final unwatermarked files are shared via digital download link.",
    ownership: "The Agent is granted a non-exclusive license to use the media for marketing this specific listing. Photographer retains copyright.",
    clauses: [
      "Property Prep: The Listing Agent must ensure the home is clean, staged, and lights are on before the photographer's arrival.",
      "Drone Flight: Drone photography is subject to FAA regulations and weather. Reschedules due to FAA no-fly locks cost no penalty."
    ]
  },
  {
    id: "home-staging",
    title: "Real Estate Home Staging Agreement",
    category: "Real Estate",
    scope: "Selecting, delivery, and styling of furniture and art pieces to stage the main living room, master bedroom, and kitchen for real estate photos.",
    rate: "$1,500 + $300/mo rental",
    schedule: "Setup fee paid upfront. Monthly furniture rental fee billed recurring on the 1st of each staged month.",
    ownership: "All staging furniture, art, and decor remain the exclusive property of the Staging Company.",
    clauses: [
      "Damage Responsibility: The Client is liable for any scratches, stains, or damage occurring to the staged furniture during listing weeks.",
      "De-staging Window: Staging Company will remove all items within 48 hours of home closing or contract termination."
    ]
  },
  {
    id: "architectural-rendering",
    title: "3D Architectural Rendering Agreement",
    category: "Real Estate",
    scope: "Creating 3 photorealistic exterior architectural renderings and a 3D walkthrough video based on blueprints provided by the Client.",
    rate: "$1,800 Flat Fee",
    schedule: "50% upfront deposit, 50% upon delivery of final high-resolution renders.",
    ownership: "The Client acquires full commercial rights to the rendered images. Designer retains project assets.",
    clauses: [
      "Source Blueprints: The Client must provide accurate floor plans and material guidelines before work kickoff.",
      "Lighting Variations: Renders include daytime lighting setup. Sunset or night lighting variations cost an additional $100 per render."
    ]
  },
  {
    id: "dietary-nutrition",
    title: "Corporate Nutrition Consulting Contract",
    category: "Wellness",
    scope: "Designing a 4-week healthy menu template for the Client's corporate cafeteria and hosting a 90-minute wellness lunch-and-learn seminar.",
    rate: "$1,200 Flat Fee",
    schedule: "50% upfront, 50% upon seminar completion and digital menu delivery.",
    ownership: "The Client holds a corporate license to distribute the menu and wellness materials to its employees.",
    clauses: [
      "No Medical Advice: The Consultant provides educational wellness guidelines and does not prescribe medical nutrition therapy.",
      "Seminar Recording: The Client may record the seminar for internal training use only, and cannot sell or publish the video publicly."
    ]
  },
  {
    id: "yoga-instruction",
    title: "Corporate Yoga Instruction Agreement",
    category: "Wellness",
    scope: "Conducting weekly 60-minute beginner-friendly group yoga classes at the Client's corporate headquarters for up to 20 employees.",
    rate: "$120 per class",
    schedule: "Billed monthly at the end of each active service month, due net 10 terms.",
    ownership: "The Instructor retains all rights to class choreography and mindfulness audio files.",
    clauses: [
      "Liability Waiver: The Client warrants that all participating employees sign a standard liability release form prior to class attendance.",
      "Space Requirement: The Client must supply a clean, quiet workspace suitable for laying down yoga mats."
    ]
  },
  {
    id: "wardrobe-styling",
    title: "Fashion Shoot Styling Agreement",
    category: "Wellness",
    scope: "Procuring wardrobe pieces from designers, styling 4 looks on-set during a half-day editorial photoshoot, and managing garment returns.",
    rate: "$800 Flat Fee",
    schedule: "50% booking retainer, 50% paid on-set upon completion of shoot services.",
    ownership: "Creative concepts belong to the Client. Stylist retains the right to display final editorial images in their portfolio.",
    clauses: [
      "Garment Budget: The Client is responsible for setting a credit card line to cover designer rentals and security deposits.",
      "Damage to Clothes: The Client is liable for any designer garment damage, dry cleaning fees, or loss occurring during the photoshoot."
    ]
  },
  {
    id: "private-chef",
    title: "Private Chef Service Agreement",
    category: "Wellness",
    scope: "Designing weekly menus, grocery shopping, preparing 5 custom dinners, packaging meals, and cleaning the kitchen for a family of four.",
    rate: "$450 / week + Groceries",
    schedule: "Prepaid in advance on the first day of each active service week.",
    ownership: "Chef maintains catalog copyrights for all custom-designed recipes.",
    clauses: [
      "Grocery Expense: Actual grocery receipt totals will be reimbursed weekly, backed by store receipts.",
      "Kitchen Access: The Family will provide the Chef with full kitchen access and keep all prep appliances functional."
    ]
  }
];
